---

- name: Change repository Ubuntu 18.04Step 4 - Setup 'web' Roles
  copy:
    src: sources.list
    dest: /etc/apt/
    backup: yes

- name: Update repository and Upgrade packages
  apt:
    upgrade: dist
    update_cache: yes

- name: Setup timezone to America/Chicago
  timezone:
    hwclock: UTC
    name: America/Chicago

# tasks file for common
